/*
 * Unity Unit Test for Utf1
 * Auto-generated by C Unit Test Generator
 */

#include "unity.h"
#include <stdint.h>
#include <stdbool.h>

/* ============================================
 * Function Prototypes
 * ============================================ */

// Test functions
static void test_01_Utx112_Utm10_ne_Utx104_Utm10_T(void);
static void test_02_Utx112_Utm10_ne_Utx104_Utm10_F(void);
static void test_03_UtD31_Utx171_T(void);
static void test_04_UtD31_Utx171_F(void);
static void test_05_Utx104_Utm11_Utm12_eq_UtD35_T(void);
static void test_06_Utx104_Utm11_Utm12_eq_UtD35_F(void);
static void test_07_Utx112_Utm11_Utm13_eq_1_T(void);
static void test_08_Utx112_Utm11_Utm13_eq_1_F(void);
static void test_09_UtD31_Utx171_T(void);
static void test_10_UtD31_Utx171_F(void);
static void test_11_Utx104_Utm11_Utm14_eq_UtD27_T(void);
static void test_12_Utx104_Utm11_Utm14_eq_UtD27_F(void);
static void test_13_Utx119_T(void);
static void test_14_Utx119_F(void);
static void test_15_Utx104_Utm11_Utm14_eq_UtD27_T(void);
static void test_16_Utx104_Utm11_Utm14_eq_UtD27_F(void);
static void test_17_Utx119_T(void);
static void test_18_Utx119_F(void);
static void test_19_UtD38_ne_0_T(void);
static void test_20_UtD38_ne_0_F(void);
static void test_21_Utx112_Utm11_Utm13_eq_0_T(void);
static void test_22_Utx112_Utm11_Utm13_eq_0_F(void);
static void test_23_Utf7_T(void);
static void test_24_Utf7_F(void);
static void test_25_Utx112_Utm11_Utm13_eq_1_T(void);
static void test_26_Utx112_Utm11_Utm13_eq_1_F(void);
static void test_27_Utx172_Utm11_Utm15_ne_0_T(void);
static void test_28_Utx172_Utm11_Utm15_ne_0_F(void);
static void test_29_UtD32_Utx171_T(void);
static void test_30_UtD32_Utx171_F(void);
static void test_31_UtD38_eq_0_T(void);
static void test_32_UtD38_eq_0_F(void);
static void test_33_Utf7_T(void);
static void test_34_Utf7_F(void);
static void test_35_UtD32_Utx171_T(void);
static void test_36_UtD32_Utx171_F(void);
static void test_37_UtD32_Utx171_T(void);
static void test_38_UtD32_Utx171_F(void);
static void test_39_Utx26_Utx20_Utm1_Utm16_T(void);
static void test_40_Utx26_Utx20_Utm1_Utm16_F(void);
static void test_41_Utx132_T(void);
static void test_42_Utx132_F(void);
static void test_43_Utx172_Utm17_Utm18_ne_0_T(void);
static void test_44_Utx172_Utm17_Utm18_ne_0_F(void);
static void test_45_Utx44_T(void);
static void test_46_Utx44_F(void);
static void test_47_Utv8_Utm66_eq_0_T(void);
static void test_48_Utv8_Utm66_eq_0_F(void);
static void test_49_Utf22_T(void);
static void test_50_Utf22_F(void);
static void test_51_Utx91_Utm21_ne_0_T(void);
static void test_52_Utx91_Utm21_ne_0_F(void);
static void test_53_UtD40_eq_1_T(void);
static void test_54_UtD40_eq_1_F(void);
static void test_55_Utx116_Utm11_Utm23_eq_1_T(void);
static void test_56_Utx116_Utm11_Utm23_eq_1_F(void);

// Mock functions
static int16_t UtD31(void); // TODO: Adjust return type
static int16_t UtD32(void); // TODO: Adjust return type
static int16_t Utf22(void); // TODO: Adjust return type
static int16_t Utf7(void); // TODO: Adjust return type
static int16_t Utx119(void); // TODO: Adjust return type
static int16_t Utx132(void); // TODO: Adjust return type
static int16_t Utx26(void); // TODO: Adjust return type
static int16_t Utx44(void); // TODO: Adjust return type

// Test target function
static void Utf1(void); // TODO: Adjust signature

/* ============================================
 * Unity Setup and Teardown
 * ============================================ */

void setUp(void)
{
    // Initialize test environment
}

void tearDown(void)
{
    // Cleanup test environment
}

/* ============================================
 * Mock/Stub Functions
 * ============================================ */

static uint32_t mock_UtD31_call_count = 0;
static int16_t mock_UtD31_return_value = 0;

static int16_t UtD31(void)
{
    mock_UtD31_call_count++;
    return mock_UtD31_return_value;
}

static uint32_t mock_UtD32_call_count = 0;
static int16_t mock_UtD32_return_value = 0;

static int16_t UtD32(void)
{
    mock_UtD32_call_count++;
    return mock_UtD32_return_value;
}

static uint32_t mock_Utf22_call_count = 0;
static int16_t mock_Utf22_return_value = 0;

static int16_t Utf22(void)
{
    mock_Utf22_call_count++;
    return mock_Utf22_return_value;
}

static uint32_t mock_Utf7_call_count = 0;
static int16_t mock_Utf7_return_value = 0;

static int16_t Utf7(void)
{
    mock_Utf7_call_count++;
    return mock_Utf7_return_value;
}

static uint32_t mock_Utx119_call_count = 0;
static int16_t mock_Utx119_return_value = 0;

static int16_t Utx119(void)
{
    mock_Utx119_call_count++;
    return mock_Utx119_return_value;
}

static uint32_t mock_Utx132_call_count = 0;
static int16_t mock_Utx132_return_value = 0;

static int16_t Utx132(void)
{
    mock_Utx132_call_count++;
    return mock_Utx132_return_value;
}

static uint32_t mock_Utx26_call_count = 0;
static int16_t mock_Utx26_return_value = 0;

static int16_t Utx26(void)
{
    mock_Utx26_call_count++;
    return mock_Utx26_return_value;
}

static uint32_t mock_Utx44_call_count = 0;
static int16_t mock_Utx44_return_value = 0;

static int16_t Utx44(void)
{
    mock_Utx44_call_count++;
    return mock_Utx44_return_value;
}

/* ============================================
 * Test Functions
 * ============================================ */

// Test No.1
// 対象分岐: if (Utx112.Utm10 != Utx104.Utm10)
// 真偽値: T
// Utx112.Utm10 != Utx104.Utm10                       :T
// 期待動作: TODO: 期待動作を記載
static void test_01_Utx112_Utm10_ne_Utx104_Utm10_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.2
// 対象分岐: if (Utx112.Utm10 != Utx104.Utm10)
// 真偽値: F
// Utx112.Utm10 != Utx104.Utm10                       :F
// 期待動作: TODO: 期待動作を記載
static void test_02_Utx112_Utm10_ne_Utx104_Utm10_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.3
// 対象分岐: if (UtD31(Utx171)
// 真偽値: T
// UtD31(Utx171                                       :T
// 期待動作: TODO: 期待動作を記載
static void test_03_UtD31_Utx171_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD31
    mock_UtD31_call_count = 0;
    mock_UtD31_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD31_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.4
// 対象分岐: if (UtD31(Utx171)
// 真偽値: F
// UtD31(Utx171                                       :F
// 期待動作: TODO: 期待動作を記載
static void test_04_UtD31_Utx171_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD31
    mock_UtD31_call_count = 0;
    mock_UtD31_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD31_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.5
// 対象分岐: if (Utx104.Utm11.Utm12 == UtD35)
// 真偽値: T
// Utx104.Utm11.Utm12 == UtD35                        :T
// 期待動作: TODO: 期待動作を記載
static void test_05_Utx104_Utm11_Utm12_eq_UtD35_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.6
// 対象分岐: if (Utx104.Utm11.Utm12 == UtD35)
// 真偽値: F
// Utx104.Utm11.Utm12 == UtD35                        :F
// 期待動作: TODO: 期待動作を記載
static void test_06_Utx104_Utm11_Utm12_eq_UtD35_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.7
// 対象分岐: if ((Utx112.Utm11.Utm13 == 1)
// 真偽値: T
// (Utx112.Utm11.Utm13 == 1                           :T
// 期待動作: TODO: 期待動作を記載
static void test_07_Utx112_Utm11_Utm13_eq_1_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.8
// 対象分岐: if ((Utx112.Utm11.Utm13 == 1)
// 真偽値: F
// (Utx112.Utm11.Utm13 == 1                           :F
// 期待動作: TODO: 期待動作を記載
static void test_08_Utx112_Utm11_Utm13_eq_1_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.9
// 対象分岐: if (UtD31(Utx171)
// 真偽値: T
// UtD31(Utx171                                       :T
// 期待動作: TODO: 期待動作を記載
static void test_09_UtD31_Utx171_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD31
    mock_UtD31_call_count = 0;
    mock_UtD31_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD31_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.10
// 対象分岐: if (UtD31(Utx171)
// 真偽値: F
// UtD31(Utx171                                       :F
// 期待動作: TODO: 期待動作を記載
static void test_10_UtD31_Utx171_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD31
    mock_UtD31_call_count = 0;
    mock_UtD31_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD31_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.11
// 対象分岐: if ((Utx104.Utm11.Utm14 == UtD27)
// 真偽値: T
// (Utx104.Utm11.Utm14 == UtD27                       :T
// 期待動作: TODO: 期待動作を記載
static void test_11_Utx104_Utm11_Utm14_eq_UtD27_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.12
// 対象分岐: if ((Utx104.Utm11.Utm14 == UtD27)
// 真偽値: F
// (Utx104.Utm11.Utm14 == UtD27                       :F
// 期待動作: TODO: 期待動作を記載
static void test_12_Utx104_Utm11_Utm14_eq_UtD27_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.13
// 対象分岐: if (Utx119()
// 真偽値: T
// Utx119(                                            :T
// 期待動作: TODO: 期待動作を記載
static void test_13_Utx119_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx119
    mock_Utx119_call_count = 0;
    mock_Utx119_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx119_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.14
// 対象分岐: if (Utx119()
// 真偽値: F
// Utx119(                                            :F
// 期待動作: TODO: 期待動作を記載
static void test_14_Utx119_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx119
    mock_Utx119_call_count = 0;
    mock_Utx119_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx119_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.15
// 対象分岐: if (Utx104.Utm11.Utm14 == UtD27)
// 真偽値: T
// Utx104.Utm11.Utm14 == UtD27                        :T
// 期待動作: TODO: 期待動作を記載
static void test_15_Utx104_Utm11_Utm14_eq_UtD27_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.16
// 対象分岐: if (Utx104.Utm11.Utm14 == UtD27)
// 真偽値: F
// Utx104.Utm11.Utm14 == UtD27                        :F
// 期待動作: TODO: 期待動作を記載
static void test_16_Utx104_Utm11_Utm14_eq_UtD27_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.17
// 対象分岐: if (Utx119()
// 真偽値: T
// Utx119(                                            :T
// 期待動作: TODO: 期待動作を記載
static void test_17_Utx119_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx119
    mock_Utx119_call_count = 0;
    mock_Utx119_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx119_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.18
// 対象分岐: if (Utx119()
// 真偽値: F
// Utx119(                                            :F
// 期待動作: TODO: 期待動作を記載
static void test_18_Utx119_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx119
    mock_Utx119_call_count = 0;
    mock_Utx119_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx119_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.19
// 対象分岐: if (UtD38 != 0)
// 真偽値: T
// UtD38 != 0                                         :T
// 期待動作: TODO: 期待動作を記載
static void test_19_UtD38_ne_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.20
// 対象分岐: if (UtD38 != 0)
// 真偽値: F
// UtD38 != 0                                         :F
// 期待動作: TODO: 期待動作を記載
static void test_20_UtD38_ne_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.21
// 対象分岐: if (Utx112.Utm11.Utm13 == 0)
// 真偽値: T
// Utx112.Utm11.Utm13 == 0                            :T
// 期待動作: TODO: 期待動作を記載
static void test_21_Utx112_Utm11_Utm13_eq_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.22
// 対象分岐: if (Utx112.Utm11.Utm13 == 0)
// 真偽値: F
// Utx112.Utm11.Utm13 == 0                            :F
// 期待動作: TODO: 期待動作を記載
static void test_22_Utx112_Utm11_Utm13_eq_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.23
// 対象分岐: if (Utf7()
// 真偽値: T
// Utf7(                                              :T
// 期待動作: TODO: 期待動作を記載
static void test_23_Utf7_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf7
    mock_Utf7_call_count = 0;
    mock_Utf7_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf7_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.24
// 対象分岐: if (Utf7()
// 真偽値: F
// Utf7(                                              :F
// 期待動作: TODO: 期待動作を記載
static void test_24_Utf7_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf7
    mock_Utf7_call_count = 0;
    mock_Utf7_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf7_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.25
// 対象分岐: if (Utx112.Utm11.Utm13 == 1)
// 真偽値: T
// Utx112.Utm11.Utm13 == 1                            :T
// 期待動作: TODO: 期待動作を記載
static void test_25_Utx112_Utm11_Utm13_eq_1_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.26
// 対象分岐: if (Utx112.Utm11.Utm13 == 1)
// 真偽値: F
// Utx112.Utm11.Utm13 == 1                            :F
// 期待動作: TODO: 期待動作を記載
static void test_26_Utx112_Utm11_Utm13_eq_1_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.27
// 対象分岐: if (Utx172.Utm11.Utm15 != 0)
// 真偽値: T
// Utx172.Utm11.Utm15 != 0                            :T
// 期待動作: TODO: 期待動作を記載
static void test_27_Utx172_Utm11_Utm15_ne_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.28
// 対象分岐: if (Utx172.Utm11.Utm15 != 0)
// 真偽値: F
// Utx172.Utm11.Utm15 != 0                            :F
// 期待動作: TODO: 期待動作を記載
static void test_28_Utx172_Utm11_Utm15_ne_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.29
// 対象分岐: if (UtD32(Utx171)
// 真偽値: T
// UtD32(Utx171                                       :T
// 期待動作: TODO: 期待動作を記載
static void test_29_UtD32_Utx171_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.30
// 対象分岐: if (UtD32(Utx171)
// 真偽値: F
// UtD32(Utx171                                       :F
// 期待動作: TODO: 期待動作を記載
static void test_30_UtD32_Utx171_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.31
// 対象分岐: if (UtD38 == 0)
// 真偽値: T
// UtD38 == 0                                         :T
// 期待動作: TODO: 期待動作を記載
static void test_31_UtD38_eq_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.32
// 対象分岐: if (UtD38 == 0)
// 真偽値: F
// UtD38 == 0                                         :F
// 期待動作: TODO: 期待動作を記載
static void test_32_UtD38_eq_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.33
// 対象分岐: if (Utf7()
// 真偽値: T
// Utf7(                                              :T
// 期待動作: TODO: 期待動作を記載
static void test_33_Utf7_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf7
    mock_Utf7_call_count = 0;
    mock_Utf7_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf7_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.34
// 対象分岐: if (Utf7()
// 真偽値: F
// Utf7(                                              :F
// 期待動作: TODO: 期待動作を記載
static void test_34_Utf7_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf7
    mock_Utf7_call_count = 0;
    mock_Utf7_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf7_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.35
// 対象分岐: if (UtD32(Utx171)
// 真偽値: T
// UtD32(Utx171                                       :T
// 期待動作: TODO: 期待動作を記載
static void test_35_UtD32_Utx171_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.36
// 対象分岐: if (UtD32(Utx171)
// 真偽値: F
// UtD32(Utx171                                       :F
// 期待動作: TODO: 期待動作を記載
static void test_36_UtD32_Utx171_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.37
// 対象分岐: if (UtD32(Utx171)
// 真偽値: T
// UtD32(Utx171                                       :T
// 期待動作: TODO: 期待動作を記載
static void test_37_UtD32_Utx171_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.38
// 対象分岐: if (UtD32(Utx171)
// 真偽値: F
// UtD32(Utx171                                       :F
// 期待動作: TODO: 期待動作を記載
static void test_38_UtD32_Utx171_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: UtD32
    mock_UtD32_call_count = 0;
    mock_UtD32_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_UtD32_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.39
// 対象分岐: if (Utx26(Utx20.Utm1.Utm16)
// 真偽値: T
// Utx26(Utx20.Utm1.Utm16                             :T
// 期待動作: TODO: 期待動作を記載
static void test_39_Utx26_Utx20_Utm1_Utm16_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx26
    mock_Utx26_call_count = 0;
    mock_Utx26_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx26_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.40
// 対象分岐: if (Utx26(Utx20.Utm1.Utm16)
// 真偽値: F
// Utx26(Utx20.Utm1.Utm16                             :F
// 期待動作: TODO: 期待動作を記載
static void test_40_Utx26_Utx20_Utm1_Utm16_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx26
    mock_Utx26_call_count = 0;
    mock_Utx26_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx26_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.41
// 対象分岐: if (Utx132()
// 真偽値: T
// Utx132(                                            :T
// 期待動作: TODO: 期待動作を記載
static void test_41_Utx132_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx132
    mock_Utx132_call_count = 0;
    mock_Utx132_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx132_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.42
// 対象分岐: if (Utx132()
// 真偽値: F
// Utx132(                                            :F
// 期待動作: TODO: 期待動作を記載
static void test_42_Utx132_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx132
    mock_Utx132_call_count = 0;
    mock_Utx132_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx132_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.43
// 対象分岐: if (Utx172.Utm17.Utm18 != 0)
// 真偽値: T
// Utx172.Utm17.Utm18 != 0                            :T
// 期待動作: TODO: 期待動作を記載
static void test_43_Utx172_Utm17_Utm18_ne_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.44
// 対象分岐: if (Utx172.Utm17.Utm18 != 0)
// 真偽値: F
// Utx172.Utm17.Utm18 != 0                            :F
// 期待動作: TODO: 期待動作を記載
static void test_44_Utx172_Utm17_Utm18_ne_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.45
// 対象分岐: if ((Utx44()
// 真偽値: T
// (Utx44(                                            :T
// 期待動作: TODO: 期待動作を記載
static void test_45_Utx44_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx44
    mock_Utx44_call_count = 0;
    mock_Utx44_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx44_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.46
// 対象分岐: if ((Utx44()
// 真偽値: F
// (Utx44(                                            :F
// 期待動作: TODO: 期待動作を記載
static void test_46_Utx44_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utx44
    mock_Utx44_call_count = 0;
    mock_Utx44_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utx44_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.47
// 対象分岐: if (Utv8[Utm66] == 0)
// 真偽値: T
// Utv8[Utm66] == 0                                   :T
// 期待動作: TODO: 期待動作を記載
static void test_47_Utv8_Utm66_eq_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.48
// 対象分岐: if (Utv8[Utm66] == 0)
// 真偽値: F
// Utv8[Utm66] == 0                                   :F
// 期待動作: TODO: 期待動作を記載
static void test_48_Utv8_Utm66_eq_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.49
// 対象分岐: if (Utf22()
// 真偽値: T
// Utf22(                                             :T
// 期待動作: TODO: 期待動作を記載
static void test_49_Utf22_T(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf22
    mock_Utf22_call_count = 0;
    mock_Utf22_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf22_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.50
// 対象分岐: if (Utf22()
// 真偽値: F
// Utf22(                                             :F
// 期待動作: TODO: 期待動作を記載
static void test_50_Utf22_F(void)
{
    // TODO: Setup test conditions

    // Reset mock: Utf22
    mock_Utf22_call_count = 0;
    mock_Utf22_return_value = 0; // TODO: Set appropriate value

    // Execute test target function
    Utf1();

    // Assertions
    TEST_ASSERT_EQUAL(1, mock_Utf22_call_count); // TODO: Set expected count
    // TODO: Add more assertions
}

// Test No.51
// 対象分岐: if (((Utx91.Utm21 != 0)
// 真偽値: T
// ((Utx91.Utm21 != 0                                 :T
// 期待動作: TODO: 期待動作を記載
static void test_51_Utx91_Utm21_ne_0_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.52
// 対象分岐: if (((Utx91.Utm21 != 0)
// 真偽値: F
// ((Utx91.Utm21 != 0                                 :F
// 期待動作: TODO: 期待動作を記載
static void test_52_Utx91_Utm21_ne_0_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.53
// 対象分岐: if ((UtD40 == 1)
// 真偽値: T
// (UtD40 == 1                                        :T
// 期待動作: TODO: 期待動作を記載
static void test_53_UtD40_eq_1_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.54
// 対象分岐: if ((UtD40 == 1)
// 真偽値: F
// (UtD40 == 1                                        :F
// 期待動作: TODO: 期待動作を記載
static void test_54_UtD40_eq_1_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.55
// 対象分岐: if (Utx116.Utm11.Utm23 == 1)
// 真偽値: T
// Utx116.Utm11.Utm23 == 1                            :T
// 期待動作: TODO: 期待動作を記載
static void test_55_Utx116_Utm11_Utm23_eq_1_T(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

// Test No.56
// 対象分岐: if (Utx116.Utm11.Utm23 == 1)
// 真偽値: F
// Utx116.Utm11.Utm23 == 1                            :F
// 期待動作: TODO: 期待動作を記載
static void test_56_Utx116_Utm11_Utm23_eq_1_F(void)
{
    // TODO: Setup test conditions

    // Execute test target function
    Utf1();

    // Assertions
    // TODO: Add more assertions
}

/* ============================================
 * Test Target Function
 * (Copy from original source file)
 * ============================================ */

// TODO: Copy the implementation of Utf1() here
